IdeaApp/IdeaApp.UI/Controllers/HomeController.cs
using IdeaApp.Entities.Models;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace IdeaApp.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            var client = new RestClient("https://localhost:44357/api/ideas");
            var request = new RestRequest(Method.GET);

            var ideas = client.Get<List<Idea>>(request);

            return View(ideas.Data);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

IdeaApp/IdeaApp.UI/Controllers/IdeasController.cs
using IdeaApp.Entities.Models;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IdeaApp.UI.Controllers
{
    public class IdeasController : Controller
    {
        // GET: Ideas
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Details(int id)
        {
            var client = new RestClient("https://localhost:44357/api/ideas/" + id);
            var request = new RestRequest(Method.GET);

            var idea = client.Get<Idea>(request);

            return View(idea.Data);
        }
    }
}

IdeaApp/IdeaApp.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

IdeaApp/IdeaApp.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

IdeaApp/IdeaApp.UI/Views/Home/Index.cshtml
@using  IdeaApp.Entities.Models;

@model List<Idea>


<!--- Welcome Section -->
<div class="container-fluid padding">
    <div class="row welcome text-center">
        <div class="col-12">
            <h1 class="display-4">Idea Application</h1>
        </div>
        <hr />
        <div class="col-12">
            <p class="lead"> In a metus orci. Phasellus tempor nisi ornare, placerat mi ac, aliquet tellus. Ut convallis mauris volutpat purus scelerisque ornare. Aenean hendrerit hendrerit eros, porttitor hendrerit risus accumsan condimentum. Sed tempor a odio at bibendum. Quisque vehicula convallis purus at ornare. Curabitur aliquam nulla nec est commodo feugiat. Aliquam suscipit consequat facilisis. Mauris et aliquam lectus.</p>
        </div>
    </div>
</div>

<!--- Two Column Section -->
<div class="container-fluid padding features">
    <div class="row text-center padding">
        <div class="col-xs-12 col-sm-6 col-md-6 idea-feature">
            <i class="far fa-lightbulb features-icon "></i>
            <h3>Submit an idea</h3>
            <p>Morbi vel leo id nisl ornare dictum. Nulla finibus semper tempor. Sed ut nisl ut nisl maximus efficitur. Nunc ultrices hendrerit odio at dictum</p>
            <button type="button" class="btn btn-collabortate">Collaborate</button>
        </div>
        <div class="col-xs-12 col-sm-6 col-md-6 idea-feature">
            <i class="fas fa-lightbulb  features-icon "></i>
            <h3>Share your view</h3>
            <p>Morbi vel leo id nisl ornare dictum. Nulla finibus semper tempor. Sed ut nisl ut nisl maximus efficitur. Nunc ultrices hendrerit odio at dictum</p>
            <button type="button" class="btn btn-collabortate">Collaborate</button>
        </div>

    </div>
</div>

<!--- Two Column Section -->
<div class="container-fluid padding text-pic ">
    <div class="row padding">
        <div class="col-lg-6">
            <h2>It's important for us what's in your mind...</h2>
            <p> Aenean hendrerit hendrerit eros, porttitor hendrerit risus accumsan condimentum. Sed tempor a odio at bibendum. Quisque vehicula convallis purus at ornare. Curabitur aliquam nulla nec est commodo feugiat. Aliquam suscipit consequat facilisis. Mauris et aliquam lectus.</p>
            <br />
            <p> Aenean hendrerit hendrerit eros, porttitor hendrerit risus accumsan condimentum. Sed tempor a odio at bibendum. Quisque vehicula convallis purus at ornare. Curabitur aliquam nulla nec est commodo feugiat. Aliquam suscipit consequat facilisis. Mauris et aliquam lectus.</p>
            <br />
            <p> Aenean hendrerit hendrerit eros, porttitor hendrerit risus accumsan condimentum. Sed tempor a odio at bibendum. Quisque vehicula convallis purus at ornare. Curabitur aliquam nulla nec est commodo feugiat. Aliquam suscipit consequat facilisis. Mauris et aliquam lectus.</p>
            <br />
            <!--<button type="button" class="btn btn-collabortate">Learn More</button>-->
        </div>
        <div class="col-lg-6">
            <img src="~/Content/Images/4.jpg" class="img-fluid" />
        </div>
    </div>
</div>

<!--- click Section -->
<button class="click" data-toggle="collapse" data-target="#click">Click for more</button>
<div id="click" class="collapse">
    <div class="container-fluid padding">
        <div class="row text-center">
            <div class="col-sm-6 col-md-3">
                <img class="gif" src="~/Content/Images/64e775_9a88dda98cc548538bbd19fed9c9fa3c_mv2.gif">
            </div>
            <div class="col-sm-6 col-md-3">
                <img class="gif" src="~/Content/Images/64e775_9a88dda98cc548538bbd19fed9c9fa3c_mv2.gif">
            </div>
            <div class="col-sm-6 col-md-3">
                <img class="gif" src="~/Content/Images/64e775_9a88dda98cc548538bbd19fed9c9fa3c_mv2.gif">
            </div>
            <div class="col-sm-6 col-md-3">
                <img class="gif" src="~/Content/Images/64e775_9a88dda98cc548538bbd19fed9c9fa3c_mv2.gif">
            </div>
        </div>
    </div>
</div>

<!--- Meet the team -->
<div class="container-fluid padding">
    <div class="row welcome text-center">
        <div class="col-12 recent">
            <h5 class="display-4">Recent topic</h5>
        </div>
        <hr class="light" />
    </div>
</div>

<!--- Cards -->
<div class="container-fluid  cards">

    <div class="row ">
        @foreach (var idea in Model)
        {
            <div class="col-md-6">
                <div class="card">
                    <img class="card-img-top" src="~/Content/Images/business-growth_large.jpg" />
                    <div class="card-body">
                        <h4 class="card-title">@idea.Title</h4>
                        <p class="card-text">@idea.Description</p>
                        @Html.ActionLink("See more","Details","Ideas",new { id=idea.Id },new { @class="btn btn-outline-secondary"})
                    </div>
                </div>
            </div>
        }
    </div>
</div>

<!--- Two Column Section -->
<!--- Connect -->
<div class="container-fluid padding">
    <div class="row text-center padding">
        <div class="col-12 social padding">

        </div>
        <div class="col-12 social padding">
            <a href="#"><i class="fab fa-facebook-square"></i></a>
            <a href="#"><i class="fab fa-twitter-square"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>

        </div>
    </div>
</div>

IdeaApp/IdeaApp.UI/Views/Ideas/Details.cshtml
@using IdeaApp.Entities.Models
@model Idea

<h2>@Model.Id</h2>
<h3>@Model.Title</h3>

IdeaApp/IdeaApp.UI/Views/Ideas/Index.cshtml
<h2>Ideas</h2>

IdeaApp/IdeaApp.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Idea App</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <link href="~/Content/Site.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-md navbar-light bg-light sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><img src="~/Content/Images/Logo.png" /></a>
            <!--@Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })-->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">

                <ul class="navbar-nav ml-auto">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Ideas", "Index", "Ideas")</li>
                    <li>@Html.ActionLink("Topics", "Index", "Topics")</li>
                </ul>
            </div>
        </div>
    </nav>

    <!--- Image Slider -->
    <div id="slides" class="carousel slide" data-ride="carousel">
        <ul class="carousel-indicators">
            <li data-target="#slides" data-slide-to="0" class="active"></li>
            <li data-target="#slides" data-slide-to="1"></li>
            <li data-target="#slides" data-slide-to="2"></li>

        </ul>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/Content/Images/2.jpg" />
                <div class="carousel-caption">
                    <h1 class="display-2">Join us and share your idea</h1>
                    <button type="button" class="btn btn-idea btn-lg"> Collaborate On Ideas</button>
                    <button type="button" class="btn btn-topic btn-outline-light btn-lg"> Collaborate On Topics</button>
                </div>
            </div>
            <div class="carousel-item">
                <img src="~/Content/Images/3.jpg" />
            </div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()

    </div>
    <hr />
    <!--- Footer -->
    <footer>
        <div class="container-fluid padding">
            <div class="row text-center">
                <div class="col-md-4">
                    <h4>ADDRESS</h4>
                    <hr class="light" />
                    <p>1550 Sherberook</p>
                </div>
                <div class="col-md-4">
                    <h4>PHONE</h4>
                    <hr class="light" />
                    <p>514-505-5955</p>
                </div>
                <div class="col-md-4">
                    <h4>EMAIL</h4>
                    <hr class="light" />
                    <p>email@idea.com</p>
                </div>

                <div class="col-12">
                    <hr class="light" />
                    <h5>&copy; www.idea.com</h5>
                </div>

            </div>
        </div>

    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>-->